import { createFileRoute } from "@tanstack/react-router";
import { PublicNavbar } from "@/components/landing/PublicNavbar";
import {
  DocumentShowcase,
  FAQ,
  FinalCTA,
  Footer,
  Hero,
  HowItWorks,
  LiveDemo,
  NigerianContext,
  Pricing,
  Testimonials,
} from "@/components/landing/Sections";

const title = "DocuAI — Nigerian Business Documents Generated by AI";
const description =
  "Generate Nigerian-context contracts, proposals, HR letters and invoices in seconds. Labour Act compliant, CAC-ready, Naira-first. 20 document types.";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title },
      { name: "description", content: description },
      { property: "og:title", content: title },
      { property: "og:description", content: description },
    ],
  }),
  component: Landing,
});

function Landing() {
  return (
    <div className="min-h-screen bg-background">
      <PublicNavbar />
      <main>
        <Hero />
        <HowItWorks />
        <DocumentShowcase />
        <LiveDemo />
        <NigerianContext />
        <Testimonials />
        <Pricing />
        <FAQ />
        <FinalCTA />
      </main>
      <Footer />
    </div>
  );
}
