import { Link } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { Check, Star, Sparkles, ArrowRight } from "lucide-react";
import { Logo } from "@/components/brand/Logo";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { CATEGORY_LABELS, DOCUMENT_TYPES, formatNaira } from "@/lib/documentTypes";
import { SAMPLE_DOCUMENT } from "@/mock/data";

export function Hero() {
  return (
    <section className="relative overflow-hidden border-b border-border bg-card">
      <div className="bg-grid-blue pointer-events-none absolute inset-0 opacity-40 [mask-image:radial-gradient(ellipse_at_top_right,black,transparent_70%)]" />
      <div className="relative mx-auto grid max-w-7xl items-center gap-12 px-4 py-16 sm:px-6 lg:grid-cols-[55%_45%] lg:py-24">
        <div className="animate-in fade-in slide-in-from-bottom-4 duration-700">
          <span className="inline-flex items-center gap-2 rounded-full border border-primary-soft bg-primary-tint px-3 py-1 text-xs font-semibold text-primary-dark">
            🇳🇬 Built for Nigerian Business
          </span>
          <h1 className="mt-6 text-4xl font-extrabold leading-[1.06] text-foreground sm:text-5xl lg:text-[52px]">
            Professional Business Documents Generated by{" "}
            <span className="text-gradient-blue">AI</span> in Seconds
          </h1>
          <p className="mt-5 max-w-[480px] text-[17px] leading-relaxed text-muted-foreground">
            DocuAI generates Nigerian-context business documents — contracts, proposals, HR
            letters, invoices, and more — instantly. No lawyer, no template hunting, no stress.
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            <Button asChild size="lg" className="bg-gradient-blue h-12 px-6 shadow-sm">
              <Link to="/register">Generate Free Document</Link>
            </Button>
            <Button
              asChild
              size="lg"
              variant="outline"
              className="h-12 border-primary-soft px-6 text-primary hover:bg-primary-tint"
            >
              <a href="#how">See How It Works</a>
            </Button>
          </div>
          <ul className="mt-8 grid gap-2 text-sm text-muted-foreground sm:grid-cols-2">
            {[
              "Nigerian Labour Act compliant",
              "CAC-ready formats",
              "Download as PDF & Word",
              `${DOCUMENT_TYPES.length} document types`,
            ].map((t) => (
              <li key={t} className="flex items-center gap-2">
                <Check className="h-4 w-4 text-success" strokeWidth={3} />
                {t}
              </li>
            ))}
          </ul>
        </div>

        <div className="relative">
          <div className="paper animate-float mx-auto max-w-md rounded-lg">
            <div className="bg-gradient-blue rounded-t-lg px-6 py-4">
              <p className="font-display text-xs font-bold uppercase tracking-widest text-primary-foreground/80">
                Zenith Retail Limited · RC 1849302
              </p>
              <p className="font-display text-lg font-bold text-primary-foreground">
                Contract of Employment
              </p>
            </div>
            <div className="space-y-2.5 px-6 py-6 text-[11px] leading-relaxed">
              <p className="font-bold">1. COMMENCEMENT AND PROBATION</p>
              <p>
                This contract commences on 01/09/2026 subject to a probationary period of three
                (3) months.
              </p>
              <p className="font-bold">3. REMUNERATION</p>
              <p>
                Gross monthly salary of {formatNaira(850000)}, payable on the 25th day of each
                month, with pension remitted per the Pension Reform Act 2014.
              </p>
              <div className="space-y-1.5 pt-2">
                <div className="h-1.5 w-full rounded bg-secondary" />
                <div className="h-1.5 w-11/12 rounded bg-secondary" />
                <div className="h-1.5 w-9/12 rounded bg-secondary" />
              </div>
              <div className="flex justify-between pt-6 text-[10px] font-semibold">
                <span className="border-t border-foreground pt-1">Employer</span>
                <span className="border-t border-foreground pt-1">Employee</span>
              </div>
            </div>
          </div>

          <FloatCard className="-left-2 top-6" delay="0.4s">
            ⚡ Generated in 8 seconds
          </FloatCard>
          <FloatCard className="-right-1 top-1/2" delay="1.1s">
            📄 PDF + Word download
          </FloatCard>
          <FloatCard className="bottom-4 left-6" delay="1.8s">
            🇳🇬 Nigerian context
          </FloatCard>
        </div>
      </div>
    </section>
  );
}

function FloatCard({
  children,
  className,
  delay,
}: {
  children: React.ReactNode;
  className?: string;
  delay: string;
}) {
  return (
    <div
      style={{ animationDelay: delay }}
      className={`animate-float absolute hidden rounded-lg border border-border bg-card px-3 py-2 text-xs font-semibold shadow-card lg:block ${className}`}
    >
      {children}
    </div>
  );
}

function SectionHead({
  label,
  title,
  sub,
  light,
}: {
  label?: string;
  title: string;
  sub?: string;
  light?: boolean;
}) {
  return (
    <div className="mx-auto max-w-2xl text-center">
      {label && <p className="eyebrow">{label}</p>}
      <h2
        className={`mt-3 text-3xl font-extrabold sm:text-[38px] ${light ? "text-primary-foreground" : "text-foreground"}`}
      >
        {title}
      </h2>
      {sub && (
        <p className={`mt-3 text-base ${light ? "text-primary-foreground/80" : "text-muted-foreground"}`}>
          {sub}
        </p>
      )}
    </div>
  );
}

export function HowItWorks() {
  const steps = [
    {
      n: "01",
      icon: "📝",
      title: "Fill Simple Form",
      body: "Tell us the basic details — parties involved, terms, dates, and preferences.",
    },
    {
      n: "02",
      icon: "🤖",
      title: "AI Generates",
      body: "Our AI writes a complete, professional, Nigerian-context document in under 10 seconds.",
    },
    {
      n: "03",
      icon: "✏️",
      title: "Edit & Download",
      body: "Review the document, make edits inline, then download as PDF or Word. Done.",
    },
  ];
  return (
    <section id="how" className="mx-auto max-w-7xl px-4 py-20 sm:px-6">
      <SectionHead
        label="How it works"
        title="From Input to Professional Document in Seconds"
      />
      <div className="mt-12 grid gap-6 md:grid-cols-3">
        {steps.map((s, i) => (
          <div
            key={s.n}
            style={{ animationDelay: `${i * 120}ms` }}
            className="animate-in fade-in slide-in-from-bottom-3 rounded-lg border border-border bg-card p-7 shadow-card duration-700"
          >
            <span className="font-display text-4xl font-extrabold text-primary-soft">{s.n}</span>
            <div className="mt-3 text-2xl">{s.icon}</div>
            <h3 className="mt-3 text-lg font-bold">{s.title}</h3>
            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{s.body}</p>
          </div>
        ))}
      </div>
    </section>
  );
}

export function DocumentShowcase() {
  const cats = (["business", "legal", "hr", "finance"] as const).map((c) => ({
    key: c,
    label: CATEGORY_LABELS[c],
    icon: { business: "📋", legal: "⚖️", hr: "👥", finance: "💰" }[c],
    docs: DOCUMENT_TYPES.filter((d) => d.category === c),
  }));

  return (
    <section id="templates" className="border-y border-border bg-card py-20">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <SectionHead label="Document types" title="Every Document Your Business Needs" />
        <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
          {cats.map((c) => (
            <div
              key={c.key}
              className="group rounded-lg border border-border border-t-4 border-t-primary bg-card p-6 shadow-card transition-all hover:-translate-y-1 hover:shadow-lift"
            >
              <div className="text-2xl">{c.icon}</div>
              <h3 className="mt-3 font-display text-base font-bold">
                {c.label}{" "}
                <span className="text-muted-foreground">({c.docs.length})</span>
              </h3>
              <ul className="mt-3 space-y-1.5 text-sm text-muted-foreground">
                {c.docs.map((d) => (
                  <li key={d.id} className="flex items-start gap-1.5">
                    <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-primary-soft" />
                    {d.name}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

export function LiveDemo() {
  const [text, setText] = useState("");
  const [running, setRunning] = useState(false);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);
  const excerpt = SAMPLE_DOCUMENT.slice(0, 720);

  useEffect(() => {
    return () => {
      if (timer.current) clearInterval(timer.current);
    };
  }, []);

  const run = () => {
    if (timer.current) clearInterval(timer.current);
    setText("");
    setRunning(true);
    let i = 0;
    timer.current = setInterval(() => {
      i += 6;
      setText(excerpt.slice(0, i));
      if (i >= excerpt.length) {
        clearInterval(timer.current!);
        setRunning(false);
      }
    }, 16);
  };

  return (
    <section id="features" className="mx-auto max-w-7xl px-4 py-20 sm:px-6">
      <SectionHead label="Live demo" title="Watch DocuAI Work" />
      <div className="mt-12 grid gap-6 lg:grid-cols-2">
        <div className="rounded-lg border border-border bg-card p-6 shadow-card">
          <div className="space-y-4">
            <div className="space-y-1.5">
              <Label htmlFor="demo-parties">Parties involved</Label>
              <Input id="demo-parties" defaultValue="Zenith Retail Ltd & Adeyinka Fashola" />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="demo-type">Type of contract</Label>
              <Input id="demo-type" defaultValue="Employment Contract" />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="demo-terms">Key terms</Label>
              <Input id="demo-terms" defaultValue="₦850,000/month, 3-month probation, Lagos" />
            </div>
            <Button onClick={run} disabled={running} className="bg-gradient-blue w-full">
              <Sparkles className="mr-1.5 h-4 w-4" />
              {running ? "Generating…" : "Generate Sample"}
            </Button>
          </div>
        </div>
        <div className="paper min-h-[320px] rounded-lg p-6 text-[12px] leading-relaxed">
          {text ? (
            <pre className="whitespace-pre-wrap font-document">{text}</pre>
          ) : (
            <p className="font-sans text-sm text-muted-foreground">
              Your generated document preview will appear here.
            </p>
          )}
        </div>
      </div>
      <p className="mt-6 text-center text-sm font-medium text-muted-foreground">
        This took 6 seconds.{" "}
        <Link to="/register" className="text-primary underline-offset-4 hover:underline">
          Sign up to generate yours.
        </Link>
      </p>
    </section>
  );
}

export function NigerianContext() {
  const cols = [
    {
      icon: "⚖️",
      title: "Legal Compliance",
      body: "Documents reference the Nigerian Labour Act 2004, CAMA 2020, and relevant Nigerian statutes. Foreign tools don't know this.",
    },
    {
      icon: "🏛️",
      title: "CAC Ready",
      body: "Company documents formatted for Corporate Affairs Commission requirements and Nigerian business registration standards.",
    },
    {
      icon: "💱",
      title: "Naira First",
      body: "All financial documents use Naira (₦) formatting, Nigerian tax references, and local business payment terms.",
    },
  ];
  return (
    <section id="nigeria" className="bg-gradient-blue py-20">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <SectionHead light title="Built for Nigeria. Unlike Any Other Tool." />
        <div className="mt-12 grid gap-6 md:grid-cols-3">
          {cols.map((c) => (
            <div
              key={c.title}
              className="rounded-lg border border-primary-foreground/15 bg-primary-foreground/10 p-7 backdrop-blur"
            >
              <div className="text-2xl">{c.icon}</div>
              <h3 className="mt-3 font-display text-lg font-bold text-primary-foreground">
                {c.title}
              </h3>
              <p className="mt-2 text-sm leading-relaxed text-primary-foreground/85">{c.body}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

export function Testimonials() {
  const items = [
    {
      name: "Chiamaka Obi",
      role: "HR Lead, Fintech · Lagos",
      quote:
        "We issue appointment and query letters weekly. DocuAI drafts them with the right Labour Act language in seconds.",
    },
    {
      name: "Musa Ibrahim",
      role: "MD, Agro Exports · Kano",
      quote:
        "Proforma invoices in Naira with proper Nigerian payment terms. My bank accepted the first one without questions.",
    },
    {
      name: "Tolu Ajayi",
      role: "Consultant · Port Harcourt",
      quote:
        "I stopped hunting for templates. Service agreements come out client-ready and I only tweak the commercials.",
    },
  ];
  return (
    <section className="border-y border-border bg-card py-20">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <SectionHead label="Testimonials" title="Trusted by Nigerian Businesses" />
        <div className="mt-12 grid gap-6 md:grid-cols-3">
          {items.map((t) => (
            <figure key={t.name} className="rounded-lg border border-border bg-background p-6 shadow-card">
              <div className="flex gap-0.5 text-gold">
                {Array.from({ length: 5 }).map((_, i) => (
                  <Star key={i} className="h-4 w-4 fill-current" />
                ))}
              </div>
              <blockquote className="mt-4 text-sm leading-relaxed text-foreground">
                “{t.quote}”
              </blockquote>
              <figcaption className="mt-4 text-sm">
                <span className="font-semibold">{t.name}</span>
                <span className="block text-muted-foreground">{t.role}</span>
              </figcaption>
            </figure>
          ))}
        </div>
      </div>
    </section>
  );
}

export function Pricing() {
  const [annual, setAnnual] = useState(false);
  const price = (monthly: number) =>
    monthly === 0 ? "₦0" : formatNaira(annual ? Math.round(monthly * 0.8) : monthly);

  const plans = [
    {
      name: "Free Trial",
      icon: "🆓",
      monthly: 0,
      features: [
        "3 documents (one-time)",
        "All document types",
        "PDF download only",
        "Basic AI generation",
        "No credit card required",
      ],
    },
    {
      name: "Professional",
      icon: "🚀",
      monthly: 8000,
      popular: true,
      features: [
        "Unlimited documents",
        `All ${DOCUMENT_TYPES.length} document types`,
        "PDF + Word download",
        "Advanced AI generation",
        "Edit & save documents",
        "Unlimited document history",
        "Priority generation speed",
        "Email support",
      ],
    },
    {
      name: "Business",
      icon: "🏢",
      monthly: 20000,
      features: [
        "Everything in Professional",
        "Team members (up to 5)",
        "Custom company branding",
        "Company letterhead upload",
        "Custom document templates",
        "API access (coming soon)",
        "Dedicated support",
      ],
    },
  ];

  return (
    <section id="pricing" className="mx-auto max-w-7xl px-4 py-20 sm:px-6">
      <SectionHead label="Pricing" title="Simple, Transparent Pricing" />
      <div className="mt-6 flex items-center justify-center gap-3 text-sm font-medium">
        <span className={annual ? "text-muted-foreground" : "text-foreground"}>Monthly</span>
        <Switch checked={annual} onCheckedChange={setAnnual} aria-label="Toggle annual billing" />
        <span className={annual ? "text-foreground" : "text-muted-foreground"}>
          Annual <span className="text-success">(save 20%)</span>
        </span>
      </div>
      <div className="mt-10 grid gap-6 lg:grid-cols-3">
        {plans.map((p) => (
          <div
            key={p.name}
            className={`relative rounded-lg border bg-card p-7 shadow-card transition-all hover:-translate-y-1 ${
              p.popular ? "border-primary shadow-lift" : "border-border"
            }`}
          >
            {p.popular && (
              <span className="absolute -top-3 left-7 rounded-full bg-primary px-3 py-1 text-[11px] font-bold uppercase tracking-wider text-primary-foreground">
                Most popular
              </span>
            )}
            <div className="text-2xl">{p.icon}</div>
            <h3 className="mt-3 font-display text-xl font-bold">{p.name}</h3>
            <p className="mt-3">
              <span className="font-display text-3xl font-extrabold">{price(p.monthly)}</span>
              {p.monthly > 0 && <span className="text-sm text-muted-foreground">/month</span>}
            </p>
            <ul className="mt-5 space-y-2.5 text-sm">
              {p.features.map((f) => (
                <li key={f} className="flex items-start gap-2">
                  <Check className="mt-0.5 h-4 w-4 shrink-0 text-success" strokeWidth={3} />
                  <span className="text-muted-foreground">{f}</span>
                </li>
              ))}
            </ul>
            <Button
              asChild
              className={`mt-6 w-full ${p.popular ? "bg-gradient-blue" : ""}`}
              variant={p.popular ? "default" : "outline"}
            >
              <Link to="/register">Start Free Trial</Link>
            </Button>
          </div>
        ))}
      </div>
      <p className="mt-8 text-center text-sm text-muted-foreground">
        All plans include a 14-day free trial. No credit card required to start.
      </p>
    </section>
  );
}

export function FAQ() {
  const faqs: [string, string][] = [
    [
      "Is DocuAI legally binding?",
      "DocuAI generates professionally drafted documents grounded in Nigerian statutes. Once signed by the parties, they carry the same weight as any other written agreement. For high-value or contentious matters we still recommend a review by your legal counsel.",
    ],
    [
      "Can I edit the generated documents?",
      "Yes. Every document opens in a full editor with a live paper preview, so you can adjust clauses, wording and commercials before downloading.",
    ],
    [
      "What makes DocuAI better than ChatGPT?",
      "DocuAI is purpose-built for Nigeria: Labour Act and CAMA references, CAC-ready formats, Naira formatting, structured forms per document type, and saved, downloadable documents — not a chat transcript.",
    ],
    [
      "Are my documents stored securely?",
      "Documents are stored against your account only, encrypted in transit, and never used to train third-party models.",
    ],
    [
      "Can I use my company logo?",
      "Business accounts can upload a logo and letterhead that is applied automatically to every generated document.",
    ],
    [
      "What formats can I download?",
      "PDF on all plans, plus Word (.docx) and copy-to-clipboard on Professional and Business.",
    ],
  ];
  return (
    <section className="border-t border-border bg-card py-20">
      <div className="mx-auto max-w-3xl px-4 sm:px-6">
        <SectionHead label="FAQ" title="Questions, Answered" />
        <Accordion type="single" collapsible className="mt-10">
          {faqs.map(([q, a]) => (
            <AccordionItem key={q} value={q}>
              <AccordionTrigger className="text-left font-display text-base font-semibold">
                {q}
              </AccordionTrigger>
              <AccordionContent className="text-sm leading-relaxed text-muted-foreground">
                {a}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}

export function FinalCTA() {
  return (
    <section className="bg-gradient-blue py-20">
      <div className="mx-auto max-w-3xl px-4 text-center sm:px-6">
        <h2 className="text-3xl font-extrabold text-primary-foreground sm:text-[38px]">
          Generate Your First Document Free
        </h2>
        <p className="mt-3 text-primary-foreground/85">
          Three free documents, all 20 types, no credit card needed. Your first contract is
          minutes away.
        </p>
        <Button
          asChild
          size="lg"
          className="mt-8 h-12 bg-card px-7 text-primary hover:bg-card/90"
        >
          <Link to="/register">
            Get Started Free <ArrowRight className="ml-1.5 h-4 w-4" />
          </Link>
        </Button>
      </div>
    </section>
  );
}

export function Footer() {
  const cols = [
    { title: "Product", items: ["Features", "Pricing", "Templates", "Changelog"] },
    { title: "Documents", items: ["Contracts", "HR Letters", "Invoices", "Proposals"] },
    { title: "Company", items: ["About", "Careers", "Blog", "Contact"] },
    { title: "Legal", items: ["Terms", "Privacy", "Security", "Refunds"] },
  ];
  return (
    <footer className="bg-sidebar py-14">
      <div className="mx-auto max-w-7xl px-4 sm:px-6">
        <div className="grid gap-10 lg:grid-cols-[1.4fr_repeat(4,1fr)]">
          <div>
            <Logo tone="light" />
            <p className="mt-3 max-w-xs text-sm text-sidebar-foreground/70">
              Professional Documents. Nigerian Context. AI Speed.
            </p>
          </div>
          {cols.map((c) => (
            <div key={c.title}>
              <p className="font-display text-sm font-bold text-primary-foreground">{c.title}</p>
              <ul className="mt-3 space-y-2 text-sm text-sidebar-foreground/70">
                {c.items.map((i) => (
                  <li key={i}>{i}</li>
                ))}
              </ul>
            </div>
          ))}
        </div>
        <p className="mt-12 border-t border-sidebar-border pt-6 text-sm text-sidebar-foreground/60">
          © 2026 DocuAI. Built for Nigerian Business.
        </p>
      </div>
    </footer>
  );
}
