/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardEditorRouteImport } from './routes/dashboard.editor'
import { Route as DashboardFavouritesRouteImport } from './routes/dashboard.favourites'
import { Route as DashboardNewRouteImport } from './routes/dashboard.new'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEditorRoute = DashboardEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavouritesRoute = DashboardFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/editor': typeof DashboardEditorRoute
  '/dashboard/favourites': typeof DashboardFavouritesRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/editor': typeof DashboardEditorRoute
  '/dashboard/favourites': typeof DashboardFavouritesRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/editor': typeof DashboardEditorRoute
  '/dashboard/favourites': typeof DashboardFavouritesRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/users'
    | '/dashboard/billing'
    | '/dashboard/documents'
    | '/dashboard/editor'
    | '/dashboard/favourites'
    | '/dashboard/new'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/users'
    | '/dashboard/billing'
    | '/dashboard/documents'
    | '/dashboard/editor'
    | '/dashboard/favourites'
    | '/dashboard/new'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/admin/users'
    | '/dashboard/billing'
    | '/dashboard/documents'
    | '/dashboard/editor'
    | '/dashboard/favourites'
    | '/dashboard/new'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/editor': {
      id: '/dashboard/editor'
      path: '/editor'
      fullPath: '/dashboard/editor'
      preLoaderRoute: typeof DashboardEditorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/favourites': {
      id: '/dashboard/favourites'
      path: '/favourites'
      fullPath: '/dashboard/favourites'
      preLoaderRoute: typeof DashboardFavouritesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardEditorRoute: typeof DashboardEditorRoute
  DashboardFavouritesRoute: typeof DashboardFavouritesRoute
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardEditorRoute: DashboardEditorRoute,
  DashboardFavouritesRoute: DashboardFavouritesRoute,
  DashboardNewRoute: DashboardNewRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
